#
#  Copyright (c) 2006-2009 Apple Inc.  All Rights Reserved.
#
#  IMPORTANT NOTE:  This file is licensed only for use on Apple-branded computers
#  and is subject to the terms and conditions of the Apple Software License Agreement
#  accompanying the package this file is a part of.  You may not port this file to
#  another platform without Apple's written consent.
#

ERR_ALLREADY_STREAMABLE = -1
ERR_MISSING_MOVIETYPE = -2
ERR_EDITING_INPLACE = -3
ERR_MISSING_VIDEOTRACK = -4
ERR_MISSING_INPUT = -5
ERR_OUTPUT_EXISTS = -6
ERR_INVALID_WIDTH = -7
ERR_INVALID_HEIGHT = -8

ERR_INVALID_KEY = -9

DEFAULT_ASPTECT_RATIOS = ["3:2", "4:3", "5:4", "16:9", "16:10"]

#DEFAULT_CMD_TIMEOUT = 60
#
## Errors for all pcast tools are defined here
#ERR_ROOT_REQUIRED = 10
#ERR_PLIST_FAILURE = 11
#ERR_CMDLINE_PARAMETERS = 12
#ERR_INVALID_AGENT_STATE = 13
#ERR_CLIENT_UNKNOWN_FAILURE = 14
#ERR_PCASTSERVER_REQUIRED = 15
#ERR_PCASTAGENT_REQUIRED = 16
#ERR_CLIENT_AUTHENTICATION_FAILURE = 17
#ERR_CLIENT_WORKFLOW_ADMINISTRATION_FAILURE = 18
#ERR_CLIENT_ACL_ADMINISTRATION_FAILURE = 19
#
#ERR_SERVER_UNAVAILABLE = 20
#ERR_SERVER_HOSTNAME = 21
#ERR_SERVER_TIMEOUT = 22
#ERR_SERVER_HTTPS_REQUIRED = 23
#ERR_SERVER_CERT_VALIDATION = 24
#ERR_SERVER_BAD_RESPONSE = 25
#ERR_SERVER_AUTH_FAILURE = 26
#ERR_SERVER_FILE_NOT_FOUND = 27
#
#ERR_SERVER_SUBMISSION_CREATE_FAILED = 30
#ERR_SERVER_FTP_UNAVAILABLE = 31
#ERR_SERVER_FILE_UPLOAD_FAILED = 32
#ERR_SERVER_FILE_COPY_FAILED = 33
#ERR_SERVER_SUBMISSION_COMPLETE_FAILED = 34
#ERR_SERVER_BIND_FAILED = 35
#ERR_SERVER_CAMERA_CMD_FAILED = 36
#ERR_SERVER_UNKNOWN_FAILURE = 37
#
#ERR_CMD_CANCELED = 100

